#Simple makefile

all: nameGen shopGen settlementGen region

nameGen:
	gcc -Wall -c nameGen.c -o nameGen.o

shopGen:
	gcc -Wall -c shopGen.c -o shopGen.o

settlementGen:
	gcc -Wall -c settlementGen.c -o settlementGen.o

region:
	gcc -Wall -c region.c -o region.o

clean:
	-rm -f *.o
